db:
  driver-class-name: "com.mysql.cj.jdbc.Driver"
  url: "jdbc:mysql://localhost:3306/hr_be_api"
  username: root
  password: fake123

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
