db:
  driver-class-name: "com.mysql.cj.jdbc.Driver"
  url: "jdbc:mysql://localhost:port/database_name"
  username: ${db.username}
  password: ${db.password}

spring:
  mail:
    host: smtp.live.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
